name: Linux CI
on:
  - pull_request
  - push
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CXX: ${{ matrix.compiler }}
      INSPIRCD_DEBUG: 1
      INSPIRCD_VERBOSE: 1
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update --assume-yes
          sudo apt-get install --assume-yes --no-install-recommends \
            clang \
            g++ \
            git \
            libc++-dev \
            libc++abi-dev \
            libgnutls28-dev \
            libldap2-dev \
            libmaxminddb-dev \
            libmbedtls-dev \
            libmysqlclient-dev \
            libpcre3-dev \
            libpq-dev \
            libre2-dev \
            libsqlite3-dev \
            libssl-dev \
            libtre-dev \
            make \
            pkg-config
      - name: Run configure
        run: |
          ./configure --enable-extras "geo_maxmind ldap mysql pgsql regex_pcre regex_posix regex_re2 regex_tre sqlite3 ssl_gnutls ssl_mbedtls ssl_openssl sslrehashsignal"
          ./configure --development --disable-auto-extras --socketengine ${{ matrix.socketengine }}
      - name: Build core
        run: |
          INSPIRCD_TARGET=inspircd make --jobs $(($(getconf _NPROCESSORS_ONLN) + 1))
      - name: Build modules
        run: |
          INSPIRCD_TARGET=modules make --jobs $(($(getconf _NPROCESSORS_ONLN) + 1))
      - name: Install
        run: |
          make install
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - clang++
          - g++
        socketengine:
          - epoll
          - poll
          - select
